import { City, Review, DashboardStats } from '@/types';

export const MOCK_CITIES: City[] = [
  {
    id: '1',
    name: '부산',
    region: 'yeongnam',
    rating: 4.2,
    monthlyCost: 1200000,
    internetSpeed: 500,
    currentNomads: 127,
    image: '/images/busan.jpg',
    tags: ['#해변근처', '#카페천국', '#교통편리'],
    description: '바다와 함께하는 노마드 라이프',
    popularityTrend: 12,
  },
  {
    id: '2',
    name: '대전',
    region: 'chungcheong',
    rating: 4.0,
    monthlyCost: 950000,
    internetSpeed: 800,
    currentNomads: 234,
    image: '/images/daejeon.jpg',
    tags: ['#교통편리', '#비용절약', '#문화생활'],
    description: '균형 잡힌 노마드 도시',
    popularityTrend: 8,
  },
  {
    id: '3',
    name: '제주',
    region: 'jeju',
    rating: 4.7,
    monthlyCost: 1450000,
    internetSpeed: 300,
    currentNomads: 89,
    image: '/images/jeju.jpg',
    tags: ['#자연친화', '#휴양형', '#해변근처'],
    description: '자연 속에서의 힐링 노마드',
    popularityTrend: 45,
  },
  {
    id: '4',
    name: '전주',
    region: 'honam',
    rating: 3.9,
    monthlyCost: 800000,
    internetSpeed: 400,
    currentNomads: 145,
    image: '/images/jeonju.jpg',
    tags: ['#문화생활', '#비용절약', '#전통'],
    description: '전통과 현대가 공존하는 도시',
    popularityTrend: 25,
  },
  {
    id: '5',
    name: '강릉',
    region: 'gangwon',
    rating: 4.1,
    monthlyCost: 1100000,
    internetSpeed: 350,
    currentNomads: 156,
    image: '/images/gangneung.jpg',
    tags: ['#해변근처', '#자연친화', '#카페천국'],
    description: '바다와 커피의 도시',
    popularityTrend: 18,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    userId: '1',
    userName: '김노마드',
    cityId: '1',
    cityName: '부산',
    content: '해운대 바다뷰 카페에서 일하니까 집중이... 잘 안돼요ㅋㅋ',
    rating: 4,
    likes: 124,
    dislikes: 8,
    comments: 23,
    createdAt: '3시간전',
  },
  {
    id: '2',
    userId: '2',
    userName: '박디지털',
    cityId: '3',
    cityName: '제주',
    content: '제주 한달살기 후기: 한라산 뷰 + 좋은 사람들 = 최고!',
    rating: 5,
    likes: 89,
    dislikes: 3,
    comments: 45,
    createdAt: '1일전',
  },
  {
    id: '3',
    userId: '3',
    userName: '이원격',
    cityId: '2',
    cityName: '대전',
    content: '대전은 진짜 숨겨진 보석 같은 도시. 생활비도 저렴하고 인터넷도 빨라요',
    rating: 4,
    likes: 67,
    dislikes: 2,
    comments: 18,
    createdAt: '2일전',
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalNomads: 2847,
  activeCities: 42,
  monthlyReviews: 1234,
  trendingCity: {
    name: '전주',
    trend: 45,
  },
};